name: CI

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: deploy
        uses: seanmiddleditch/gha-publish-to-git@master
        with:
          repository: https://github.com/xbl/actions_test_target
          github_token: '${{ secrets.token  }}'
          source_folder: static/html
          target_folder: static/app
        if: success() && github.event == 'push'
