name: CI

on: [push]

jobs:
  publish:
    - uses: actions/checkout@master
    - run: |
        sh echo "hello world!"
    - uses: seanmiddleditch/gha-publish-to-git@master
      with:
        repository: https://github.com/xbl/actions_test_target
        github_token: '${{ secrets.token  }}'
        source_folder: static/html
        target_folder: static/app
      if: success() && github.event == 'push'
